// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package profiling.actions;

import com.mendix.core.Core;
import com.mendix.logging.LogLevel;
import com.mendix.logging.LogMessage;
import com.mendix.logging.LogSubscriber;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.thirdparty.org.json.JSONObject;
import com.mendix.webui.CustomJavaAction;
import profiling.implementation.TCPClient;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class JA_LogListener_Start extends CustomJavaAction<java.lang.Void>
{
	/** @deprecated use SessionSetup.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __SessionSetup;
	private final profiling.proxies.SessionSetup SessionSetup;

	public JA_LogListener_Start(
		IContext context,
		IMendixObject _sessionSetup
	)
	{
		super(context);
		this.__SessionSetup = _sessionSetup;
		this.SessionSetup = _sessionSetup == null ? null : profiling.proxies.SessionSetup.initialize(getContext(), _sessionSetup);
	}

	@java.lang.Override
	public java.lang.Void executeAction() throws Exception
	{
		// BEGIN USER CODE
		TCPClient client = TCPClient.INSTANCE;

		if (this.SessionSetup != null) {
			JSONObject jo = new JSONObject();
			jo.put("type", "ProfilerStart");
			jo.put("identifier", this.SessionSetup.getidentifier());
			if (SessionSetup.getdo_filter_flow()) {
				jo.put("flow_name", SessionSetup.getflow_filter());
			}

			client.sendMessage(jo.toString());
		}

		client.startLogging();
		
		return null;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_LogListener_Start";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
